# Generated by Django 4.0 on 2021-12-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demineur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demineur',
            name='Score',
            field=models.IntegerField(default=0),
        ),
    ]
