# Generated by Django 4.0 on 2021-12-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demineur', '0004_remove_demineur_speudo_demineur_pseudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demineur',
            old_name='Pseudo',
            new_name='Login',
        ),
        migrations.RenameField(
            model_name='demineur',
            old_name='MDP',
            new_name='Password',
        ),
    ]
